// Map
export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const SELECT_RESTAURANT_REQUEST = 'SELECT_RESTAURANT_REQUEST';
export const SELECT_RESTAURANT_RESPONSE = 'SELECT_RESTAURANT_RESPONSE';
// Map Settings
export const SET_RADIUS = 'SET_RADIUS';
// Search
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const NEW_SEARCH = 'NEW_SEARCH';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const AUTOCOMPLETE_ADDRESS_REQUEST = 'AUTOCOMPLETE_ADDRESS_REQUEST';
export const AUTOCOMPLETE_ADDRESS_RESPONSE = 'AUTOCOMPLETE_ADDRESS_RESPONSE';
export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';
export const FIND_RESTAURANTS_REQUEST = 'FIND_RESTAURANTS_REQUEST';
export const FIND_RESTAURANTS_RESPONSE = 'FIND_RESTAURANTS_RESPONSE';
// Review
export const SEARCH_FOOD_REQUEST = 'SEARCH_FOOD_REQUEST';
export const SEARCH_FOOD_RESPONSE = 'SEARCH_FOOD_RESPONSE';
